/** Aggregated tool metrics from evolution API. */
export interface ToolAggregate {
  tool_name: string;
  call_count: number;
  success_rate: number;
  avg_duration_ms: number;
}

/** Aggregated retrieval metrics from evolution API. */
export interface RetrievalAggregate {
  source: string;
  query_count: number;
  usage_rate: number;
  avg_score: number;
}

/** Evolution suggestion generated by the suggestion engine. */
export interface EvolutionSuggestion {
  id: string;
  agent_id: string;
  suggestion_type: "threshold" | "tool_order" | "skill_add";
  suggestion: string;
  rationale: string;
  parameters: Record<string, unknown> | null;
  status: "pending" | "approved" | "rejected" | "applying" | "applied" | "rolled_back";
  reviewed_by: string | null;
  reviewed_at: string | null;
  created_at: string;
  applied_at?: string | null;
  applied_by?: string | null;
  rolled_back_at?: string | null;
  rolled_back_by?: string | null;
  /** Exact config change made on apply (absent for advisory/legacy rows). */
  applied_change?: AgentConfigChange | null;
  state_version?: number;
}

/** A JSON value plus whether the key existed at all (absence matters for rollback). */
export interface ConfigValue {
  present: boolean;
  value?: unknown;
}

/** One mutation of an agent JSONB config column at a key path. */
export interface AgentConfigChange {
  column: string;
  path: string[];
  before: ConfigValue;
  after: ConfigValue;
}

/** Append-only audit record of a suggestion transition. */
export interface EvolutionEvent {
  id: string;
  suggestion_id: string;
  action: string;
  from_status: string;
  to_status: string;
  actor: string;
  detail?: Record<string, unknown> | null;
  created_at: string;
}

/** Aggregated metrics response from GET /evolution/metrics?aggregate=true. */
export interface AggregatedMetrics {
  tool_aggregates: ToolAggregate[];
  retrieval_aggregates: RetrievalAggregate[];
}

/** Adaptation guardrails stored in agent other_config. */
export interface AdaptationGuardrails {
  max_delta_per_cycle: number;
  min_data_points: number;
  rollback_on_drop_pct: number;
  locked_params: string[];
}
